import { useState } from 'react';
import {
  BarChart, Bar, LineChart, Line, PieChart, Pie, Cell,
  XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid
} from 'recharts';
import StatusBadge from '../shared/StatusBadge.jsx';

const COLORS = ['#D32F2F', '#FF9800', '#1565C0', '#2E7D32', '#6A1B9A', '#00838F', '#E65100', '#558B2F'];

function SummaryCard({ label, value, sub, color = '#3b82f6', pulse = false }) {
  return (
    <div className="summary-card">
      <div className="summary-card-label">{label}</div>
      <div className="summary-card-value" style={{ color }}>
        {pulse && <span className="pulse-dot" style={{ background: color }} />}
        {value}
      </div>
      {sub && <div className="summary-card-sub">{sub}</div>}
    </div>
  );
}

const RECENT_ACTION_ICONS = {
  'Exception generated by VEE engine': '⚠',
  'Resolved': '✓',
  'Field Order': '🔧',
};

export default function Dashboard({ state, derived }) {
  if (!state || !derived) {
    return <div className="loading">Initializing simulation engine...</div>;
  }

  const recentExceptions = [...(state.exceptions || [])]
    .sort((a, b) => b.createdAt - a.createdAt)
    .slice(0, 8);

  const recentActivity = [
    ...recentExceptions.map(e => ({
      ts: e.createdAt,
      text: `[${e.id}] ${e.typeLabel} — ${e.meterID} (${e.severity})`,
      type: 'exception',
    })),
    ...(state.resolvedExceptions || []).slice(-4).map(e => ({
      ts: e.updatedAt,
      text: `[${e.id}] Resolved: ${e.typeLabel} — ${e.meterID}`,
      type: 'resolved',
    })),
  ].sort((a, b) => b.ts - a.ts).slice(0, 12);

  const openCollectors = Object.entries(derived.collectorStates).filter(([, s]) => !s.online);

  return (
    <div className="dashboard">
      {/* Summary Cards Row */}
      <div className="summary-cards">
        <SummaryCard
          label="TOTAL METERS"
          value={derived.totalMeters}
          sub="AMI endpoint devices"
          color="#1565C0"
        />
        <SummaryCard
          label="COMMUNICATING"
          value={`${derived.communicatingPct}%`}
          sub={`${derived.communicatingCount} / ${derived.totalMeters} meters`}
          color={derived.communicatingPct >= 95 ? '#2E7D32' : derived.communicatingPct >= 85 ? '#FF9800' : '#D32F2F'}
        />
        <SummaryCard
          label="OPEN EXCEPTIONS"
          value={derived.openExceptions}
          sub={`${derived.exceptionsByType.length} active types`}
          color={derived.openExceptions > 10 ? '#D32F2F' : derived.openExceptions > 0 ? '#FF9800' : '#2E7D32'}
          pulse={derived.openExceptions > 0}
        />
        <SummaryCard
          label="RESOLVED TODAY"
          value={derived.resolvedToday}
          sub={derived.avgResolutionMinutes > 0 ? `Avg ${derived.avgResolutionMinutes}m resolution` : 'No resolutions yet'}
          color="#2E7D32"
        />
        <SummaryCard
          label="PENDING FIELD ORDERS"
          value={derived.pendingFieldOrders}
          sub="Open work orders"
          color={derived.pendingFieldOrders > 5 ? '#FF9800' : '#1565C0'}
        />
        <SummaryCard
          label="BILLING READINESS"
          value={`${derived.billingReadinessPct}%`}
          sub="Accounts with clean data"
          color={derived.billingReadinessPct >= 95 ? '#2E7D32' : '#FF9800'}
        />
      </div>

      {openCollectors.length > 0 && (
        <div className="alert-banner">
          <span className="alert-icon">⚠</span>
          {openCollectors.length} COLLECTOR{openCollectors.length > 1 ? 'S' : ''} OFFLINE:{' '}
          {openCollectors.map(([id]) => id).join(', ')}
          {' '}— Downstream meters may be unreachable
        </div>
      )}

      {/* Charts Row */}
      <div className="charts-row">
        {/* Exception by type */}
        <div className="chart-panel">
          <div className="chart-title">EXCEPTION BREAKDOWN — BY TYPE</div>
          {derived.exceptionsByType.length === 0 ? (
            <div className="chart-empty">No open exceptions</div>
          ) : (
            <ResponsiveContainer width="100%" height={200}>
              <BarChart data={derived.exceptionsByType} margin={{ top: 4, right: 8, bottom: 40, left: 0 }}>
                <CartesianGrid strokeDasharray="2 4" stroke="#E0E0E0" />
                <XAxis
                  dataKey="name"
                  tick={{ fontSize: 9, fill: '#757575', fontFamily: 'monospace' }}
                  angle={-35}
                  textAnchor="end"
                  interval={0}
                />
                <YAxis tick={{ fontSize: 10, fill: '#757575' }} />
                <Tooltip
                  contentStyle={{ background: '#FFFFFF', border: '1px solid #E0E0E0', color: '#333333', fontFamily: 'monospace', fontSize: 12 }}
                />
                <Bar dataKey="value" fill="#D32F2F" />
              </BarChart>
            </ResponsiveContainer>
          )}
        </div>

        {/* 7-day exception trend */}
        <div className="chart-panel">
          <div className="chart-title">EXCEPTION TREND — LAST 7 DAYS</div>
          <ResponsiveContainer width="100%" height={200}>
            <LineChart data={state.dailyExceptionCounts || []} margin={{ top: 4, right: 8, bottom: 4, left: 0 }}>
              <CartesianGrid strokeDasharray="2 4" stroke="#E0E0E0" />
              <XAxis dataKey="date" tick={{ fontSize: 9, fill: '#757575', fontFamily: 'monospace' }} />
              <YAxis tick={{ fontSize: 10, fill: '#757575' }} />
              <Tooltip
                contentStyle={{ background: '#FFFFFF', border: '1px solid #E0E0E0', color: '#333333', fontFamily: 'monospace', fontSize: 12 }}
              />
              <Line type="monotone" dataKey="count" stroke="#FF9800" strokeWidth={2} dot={{ fill: '#FF9800', r: 3 }} />
            </LineChart>
          </ResponsiveContainer>
        </div>

        {/* Exception severity split */}
        <div className="chart-panel">
          <div className="chart-title">SEVERITY DISTRIBUTION</div>
          {(() => {
            const counts = {};
            (state.exceptions || []).forEach(e => {
              counts[e.severity] = (counts[e.severity] || 0) + 1;
            });
            const pieData = Object.entries(counts).map(([name, value]) => ({ name, value }));
            if (pieData.length === 0) return <div className="chart-empty">No open exceptions</div>;
            return (
              <ResponsiveContainer width="100%" height={200}>
                <PieChart>
                  <Pie data={pieData} cx="50%" cy="50%" outerRadius={75} dataKey="value" label={({ name, value }) => `${name}: ${value}`}
                    labelLine={{ stroke: '#9E9E9E' }}
                  >
                    {pieData.map((entry, index) => (
                      <Cell key={index} fill={entry.name === 'Error' ? '#D32F2F' : entry.name === 'Warning' ? '#FF9800' : '#1565C0'} />
                    ))}
                  </Pie>
                  <Tooltip contentStyle={{ background: '#FFFFFF', border: '1px solid #E0E0E0', color: '#333333', fontFamily: 'monospace', fontSize: 12 }} />
                </PieChart>
              </ResponsiveContainer>
            );
          })()}
        </div>
      </div>

      {/* Bottom Row */}
      <div className="bottom-row">
        {/* Open exceptions mini table */}
        <div className="mini-table-panel">
          <div className="panel-title">ACTIVE EXCEPTIONS — NEWEST FIRST</div>
          <table className="data-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>METER</th>
                <th>TYPE</th>
                <th>SEV</th>
                <th>AGE</th>
              </tr>
            </thead>
            <tbody>
              {recentExceptions.length === 0 ? (
                <tr><td colSpan={5} className="empty-row">No open exceptions</td></tr>
              ) : recentExceptions.map(exc => {
                const ageMs = (derived.simDate?.getTime() || Date.now()) - exc.createdAt;
                const ageH = Math.floor(ageMs / 3600000);
                const ageM = Math.floor((ageMs % 3600000) / 60000);
                return (
                  <tr key={exc.id}>
                    <td className="mono text-amber">{exc.id}</td>
                    <td className="mono">{exc.meterID}</td>
                    <td>{exc.typeLabel}</td>
                    <td><StatusBadge status={exc.severity} /></td>
                    <td className="mono text-dim">{ageH}h {ageM}m</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        {/* Activity log */}
        <div className="activity-panel">
          <div className="panel-title">RECENT ACTIVITY LOG</div>
          <div className="activity-log">
            {recentActivity.length === 0 ? (
              <div className="activity-empty">No recent activity</div>
            ) : recentActivity.map((item, i) => (
              <div key={i} className={`activity-item activity-${item.type}`}>
                <span className="activity-ts">{new Date(item.ts).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false })}</span>
                <span className="activity-text">{item.text}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
